schema.clear()
schema.vertexLabel('paper').create()
schema.propertyKey('paperId').Int().create()
schema.propertyKey('title').Text().create()
schema.vertexLabel('paper').properties('paperId').add()
schema.vertexLabel('paper').index('byPaperId').materialized().by('paperId').add()
schema.edgeLabel('cites').connection('paper', 'paper').create()
schema.vertexLabel('author').create()
schema.propertyKey('name').Text().create()
schema.vertexLabel('author').properties('name').add()
schema.propertyKey('weight').Double().create()
schema.edgeLabel('wrote').connection('author', 'paper').create()
schema.edgeLabel('wrote').properties('weight').add()
schema.propertyKey('authorId').Int().create()
schema.vertexLabel('author').index('byAuthorId').materialized().by('authorId').add()
